### PR TITLE
Add API Key for Auth, fixes, and enhancements.

### LINKED ISSUE #22: host_get_multiple_ids only works for single hostname
This action when ran is not working if multiple hostnames are specified. I see that the param `host` is configured as `type: string`. I've tried passing an array of values as a sting, but looking at how the Zabbix API accepts this call, it either needs to be a string with 1 value, or an array.

To me, this action needs to have its parameter changed from `type: string` to `type: array`

This is based on a few factors:
 - The way the logic used for the action that was written
 - The api param `filter` with `host` accepts a list of host names
 - There is another action that finds the ID for 1 single host name

I've tested this action to be working well by changing to `type: array` and passing an array of multiple hostnames.

If the action definition as written is a typo or mistake, I'll gladly submit the pr to adjust it while im also adding a new action.

### LINKED ISSUE #32: ack_event.yaml - param `will_close` enum with boolean type
The action `ack_event.yaml` has a parameter `will_close` with `type: boolean` but also has enum of `True, False`. When trying to use this action in the webgui it presents a list of strings for "True" and "False" but will not accept the input because it is a string, not a boolean.

Recommendation: remove `enum:` and leave default (true) as is.

### PR DESCRIPTION
**Pull request by namachieli**
From Changelog
### Changes

- `triggers/event_handler.yaml` - `alert_message` type updated to include `array`, `object` 
  with logic in `st2_dispatch.py` to handle the difference.
- `st2_dispatch.py` flags: `--st2-api-url` and `--st2-auth-url` no longer have default values.
  See code comments for details.

### Additions

- API Keys can now be used to authenticate to the ST2 API. Please see the 'Advanced Usage'
  section in the readme for more details.
- `--api-key` flag can be passed to `st2_dispatch.py` to test usage with an API Key for authentication
- `st2_dispatch.py` can now send to a user defined trigger, but defaults to `zabbix.event_handler`
- The value of `alert_message` passed in from the Zabbix macro `{ALERT.MESSAGE}` will now be evaluated
  to determine if its a JSON valid List or Dict, or a string, and passed accordingly.
- When using a JSON Dict to pass auth parameters, keys and values passed are parsed as is into options
  that can then be used in later logic.
  This means you can pass any valid option as a key:val pair (`st2_userid`, `st2_passwd`, `trigger`, etc)
  - This excludes `alert_sendto`, `alert_subject`, `alert_message` as they are parsed after the JSON Dict

### Fixes

- Corrected a bug in `ack_event.yaml` where `enum:` was applied with `type: boolean`. Fixes #32
- `host_get_multiple_ids` - `type:` is now `array` (was `string`). Fixes #22

### CODE REVIEW

**Comment by namachieli** [comment]
Please review and comment. If accepted, This PR would close #22 #23 and #30

**Comment by namachieli** [comment]
Fixing unit tests.

**Comment by namachieli** [comment]
Fixing file permissions. some files were changed to 755 from 644 for some unknown reason.

**Comment by namachieli** [comment]
Testing fix in #31 to see if it can be added to this PR

**Comment by namachieli** [comment]
Based on the details of #31, should the pack version be changed?

**Comment by userlocalhost** [comment]
Thank you for making good implementation with keeping backward compatibility.

LGTM 👍

**Pull request merged**
